### ISSUE TITLE
Adding class to img-base64 type

### ISSUE THREAD

**Issue by Amgelo563** [nice-move/remark-kroki#3]
Hi, is there a way the plugin could specify a class name when using the `img-base64` type?

I'm currently trying to target the plugin's output using CSS, and unfortunately I can't do so without a class or anything like that. As a workaround, I'm wrapping it on a div, but it doesn't work when the image gets out of the div, like when using the `docusaurus-plugin-image-zoom` plugin and zooming in.

Thanks for the great plugin, this addition could really help me on my project.

**Comment by Airkro** [comment]
Done in v0.2.10.

See: https://github.com/nice-move/remark-kroki/commit/4842d1ed1e505badf6a96eb9efb38ec1ae718e41

**Comment by Amgelo563** [comment]
This works perfectly, thanks!
